# Generated by Django 4.0.3 on 2023-04-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='vip_status',
        ),
    ]
